### ISSUE TITLE
Example without Expo?

### ISSUE THREAD

**Issue by AndrewMorsillo** [PEZ/rn-rf-shadow#10]
I'm a react-native dev but a total newbie to CLJS. How would I go about setting up this project to use vanilla react-native (no expo, no expokit)? 

I've attempted it but can't seem to figure out how to set up the entry point for vanilla rn.

**Comment by PEZ** [comment]
I'm not in the know here. I suggest asking in the #shadow-cljs and #cljsrn channels on the Clojurians Slack: http://clojurians.net

**Comment by AndrewMorsillo** [comment]
I pieced together how to do it. I'm a total Clojure newbie so I don't completely understand what's going on here, but I did the following change to app.cljs from this repo

```
(def appjson (js/require "../app.json"))

(defonce root-ref (atom nil))
(defonce root-component-ref (atom nil))

(defn render-root [app-key root]
  (let [first-call? (nil? @root-ref)]

    (reset! root-ref root)

    (if-not first-call?
      (when-let [root @root-component-ref]
        (.forceUpdate ^:js root))
      (let [Root (crc
                  #js {:componentDidMount (fn []
                                            (this-as this
                                              (reset! root-component-ref this)))
                       :componentWillUnmount (fn []
                                               (reset! root-component-ref nil))
                       :render (fn []
                                 (let [body @root-ref]
                                   (if (fn? body)
                                     (body)
                                     body)))})]

        (.registerComponent rn/AppRegistry app-key (fn [] Root))))))


(defn start
  {:dev/after-load true}
  []
  (render-root (oget appjson "name") (r/as-element [root])))
```

Then in the index.js entry point I just import the compiled js

```
import './app/index';
```

Other than that the code is the same as this repo (but on top of a bare RN project instead of expo). Once I play with it some more I'll hopefully learn enough to make a good example repo of my own. Until then hopefully this comment will help out others who might want to try the same as me.
