### ISSUE TITLE
Potentially incorrect nREPL port specified in README 

### ISSUE THREAD

**Issue by gustaver** [PEZ/rn-rf-shadow#17]
On [Line 116](https://github.com/PEZ/rn-rf-shadow/blob/master/README.md#L116) in the README, the user is prompted to connect to the nREPL on port 9000. However, as far as I can see, there is no indication that the nREPL will be started at port 9000. In my experience using the repo, shadow-cljs will start the nREPL at different ports each time it starts. 

I suggest that either a configuration is added to always start the nREPL at port 9000, or the user should be directed to use the port in `.shadow-cljs/nrepl.port`.

**Comment by PEZ** [comment]
I think this is fixed now. At least I can't find any mention of any nrepl port. 😄
