### ISSUE TITLE
Disabling live reload and enabling hot reload in web

### ISSUE THREAD

**Issue by davidpham87** [PEZ/rn-rf-shadow#3]
Hello,

It is great to see such a project as I am working on the same idea. In terms of development, did you manage to get hot reloading work with the web target? 

I can disable live reload with blocking request calls to sockjs-node in chrome, but then it blocks also live reloading.

Best regard,
David

**Comment by PEZ** [comment]
Hello! I think @neupsh mentioned he had found some (complicated) way of doing it.

**Comment by neupsh** [comment]
@davidpham87 I do the same actually. I just let shadow-cljs hotload the code and block the requests to `/sockjs-node/*`.

**Comment by davidpham87** [comment]
@neupsh How does the web browser knows that the code has been hot reloaded then? Because the code has to be compiled by webpack triggered by shadow-cljs, then how does it get hot reloaded? Do you have any repo where I could test? 

Thanks a lot!

**Comment by neupsh** [comment]
@davidpham87 I am not sure how but shadow-cljs hot-loads the changes. I can change the code and save and shadow-cljs compiles the code and loads it. Something like the following should work:
1. Run `shadow-cljs watch app` (keep this running)
2. Once shadow-cljs compiles successfully, run `yarn start web`
3. Once expo builds and bundles the js, go to localhost:19006, open devtools in chrome, disable the `sock-js-node` requests (keep the devtools open)
4. Click the "Click me, I'll count" button on the just loaded page to see the state change. 
5. Change buttons label on the source to something else and save
6. You should see that the button label changes on the page without reloading the page (with the count still intact).
At least that's what I see here. Hope this helps.

**Comment by PEZ** [comment]
Blocking the requests does not seem to be working any more. I have that blocked but it still looks like it does in this video:

https://www.youtube.com/watch?v=QsUj7HO5xDg&feature=youtu.be

Scrub to 30 minutes to find where I start showing the web version.

**Comment by cjbarre** [comment]
Hey everyone,

I found this while digging through the web: https://forums.expo.io/t/disable-reloading-for-web/44059/3

The solution mentioned by Hank:

> Yea, finally found the answer. The reloading mechanism is coming from webpack-dev-server (running in version 3.11.0 on my machine). In order to get rid of it, I
>
>    - ran expo with customize:web and selected to create a webpack.config.js
>    - added config.devServer.watchOptions.ignored = [/.*/]; to webpack.config.js

I tried this and it did work, I'm not sure if there are any downsides to it, I'm not a javascript tooling wiz.

**Comment by PEZ** [comment]
Oh, wow. Thanks! It certainly seems like you are JS tooling wiz! I will try this and update the README.

**Comment by PEZ** [comment]
Finally got around to this. Added the config to this repo.
