### ISSUE TITLE
shadow-cljs: Failed to connect to localhost

### ISSUE THREAD

**Issue by MareinK** [PEZ/rn-rf-shadow#31]
I'm running into a problem when trying this and other examples. I'm getting the below error when running `npm start` (while running `npx shadow-cljs watch app` in another terminal). I'm not sure if it's a problem with the template, with expo, or with my local environment. In any case, tips are appreciated!

```
Android Running app on moto g(8) plus

Debugger and device times have drifted by more than 60s. Please correct this by running adb shell "date `date +%m%d%H%M%Y.%S`" on your debugger machine.
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

Unable to symbolicate stack trace: The stack is null

The shadow-cljs Websocket was disconnected.
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

shadow-cljs - remote-error, Event {
  "isTrusted": false,
  "message": "Failed to connect to localhost/127.0.0.1:9630",
}
at node_modules/expo/build/logs/LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
```

**Comment by MareinK** [comment]
Someone found a workaround for this problem, see [here](https://github.com/thheller/shadow-cljs/issues/957#issuecomment-969219175).

**Comment by PEZ** [comment]
Thanks fort updating the issue! Do you think we should mention it in the README?

**Comment by MareinK** [comment]
Perhaps. It would help new users like myself who get stuck on this error. However, it seems that only a few people do encounter this error, and `shadow-cljs` is working fine with `expo` for most people. During the weeks that I was investigating this issue, nobody else seemed to have this particular problem except the person who found the workaround. But certainly I would have benefited greatly if it was mentioned in the README.

So... up to you, I guess :)

**Comment by PEZ** [comment]
You are welcome to send a PR. ❤️
