### ISSUE TITLE
npm warnings

### ISSUE THREAD

**Issue by esciafardini** [PEZ/rn-rf-shadow#38]
After running command `npm i` - there are a lot of vulnerabilities - some flagged as _critical_.

<img width="607" alt="Screen Shot 2022-10-22 at 9 25 11 PM" src="https://user-images.githubusercontent.com/51748017/197368754-c3528dd2-b417-4ea0-b5d4-44809af3d8d7.png">

**Comment by PEZ** [comment]
Thanks. Can you try `audit fix` and see if that fixes it while letting the project still work?

**Comment by esciafardini** [comment]
Tried that to no avail :(

**Comment by esciafardini** [comment]
appears to be a lot of issues with the version of expo

**Comment by esciafardini** [comment]
https://github.com/PEZ/rn-rf-shadow/pull/37/commits/e3c7322cf0dfd8c59663f7302a50f6b8571b0935 - perhaps this PR address said issues?

**Comment by PEZ** [comment]
Thanks. I had totally missed/forgotten about that PR. I merged it and have also bumped things a bit more.

We still have 27 vulnerabilities, of which 3 are critical. It's not possible to get a clean audit, I think. But all are coming from `expo-cli` which you'll only be running in dev and locally, so it shouldn't mean that an app built using the current tool chain has any known vulnerabilities.
