### ISSUE TITLE
Shadow-cljs hot reload don't work properly

### ISSUE THREAD

**Issue by PrestanceDesign** [PEZ/rn-rf-shadow#5]
Hi,

In the README, we can see :
 
> In the Expo settings for your app (shake or force touch with two fingers), disable Live Reloadinhg and Hot Reloading. (Don't worry, shadow-cljs will take care of hot reloading for you, in the most beautiful way.)

Unfortunately this doesn't work well for my test.
It's only works when I edit the main CLJS file but it's stop working for required components on root and/or subdirectories like `components/hello.cljs`, etc.

Shadow-cljs hot reload works very well for my Reagent web project.
Anybody know why that bug for React Native/Expo project ?

Best regards.
Mike

**Comment by PEZ** [comment]
That's strange. It used to work for required components.

**Comment by PrestanceDesign** [comment]
> That's strange. It used to work for required components.

Yesterday, I tried the same project with *re-natal* and figwheel handle perfectly the hot reloading for all my components.
I will retry on fresh clone rn-rf-shadow. ;)

**Comment by PrestanceDesign** [comment]
I close this issue, @thheller had given more information about this behavior : https://github.com/thheller/shadow-cljs/issues/544#issuecomment-521662073
